# Site settings
title: "Jekyll Resume Template"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Santiago Marquez Baeza"
resume_title:                   "Software Development Engineering Student"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "marquezbaezasantiago@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "639-174-7625"
resume_contact_address:         "Chapultepec, 4309, Nombre de Dios, Chihuahua, Chih"

resume_header_contact_info:     "Chapultepec, 4309, Nombre de Dios, Chihuahua, Chih • 639-174-7625 • marquezbaezasantiago@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>I am a versatile person, driven by curiosity and a passion for learning. My energy, proactivity, and strong human spirit define my approach and sense of purpose in life.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           false
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/S4nti-NPC"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  resume_facebook_url:          "https://www.facebook.com/santiago.marquez.188478"
  resume_linkedin_url:          "https://www.linkedin.com/in/santiago-marquez-baeza-030997262/"
  resume_instagram_url:         "https://www.instagram.com/santi._.mb/"
  #resume_website_url:           "http://joelglovier.com"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
